// bin2h.cpp — 把二进制文件转成 C++ 头文件字节数组
// 用法: bin2h.exe <input> <output.h>
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

static bool WriteAll(HANDLE h, const void* data, DWORD size) {
    DWORD done = 0;
    return WriteFile(h, data, size, &done, nullptr) != 0 && done == size;
}

int wmain(int argc, wchar_t** argv) {
    if (argc != 3) {
        fwprintf(stderr, L"usage: bin2h.exe <input> <output.h>\n");
        return 1;
    }
    HANDLE in = CreateFileW(argv[1], GENERIC_READ, FILE_SHARE_READ, nullptr,
                            OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (in == INVALID_HANDLE_VALUE) { fwprintf(stderr, L"open input failed\n"); return 2; }
    DWORD hi = 0, lo = GetFileSize(in, &hi);
    if (lo == INVALID_FILE_SIZE) { CloseHandle(in); return 3; }
    size_t size = ((size_t)hi << 32) | lo;
    std::vector<unsigned char> data(size);
    DWORD rd = 0;
    ReadFile(in, data.data(), (DWORD)size, &rd, nullptr);
    CloseHandle(in);
    if (rd != size) { fwprintf(stderr, L"read failed\n"); return 4; }

    HANDLE out = CreateFileW(argv[2], GENERIC_WRITE, FILE_SHARE_READ, nullptr,
                             CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (out == INVALID_HANDLE_VALUE) { fwprintf(stderr, L"open output failed\n"); return 5; }

    auto W = [&](const char* s) { return WriteAll(out, s, (DWORD)strlen(s)); };
    W("// Auto-generated by bin2h.cpp. Do not edit.\n");
    W("#pragma once\n");
    W("static const unsigned char g_payloadDll[] = {\n");
    char buf[16];
    for (size_t i = 0; i < size; ++i) {
        snprintf(buf, sizeof(buf), "%u,", (unsigned)data[i]);
        W(buf);
        if ((i & 15) == 15) W("\n");
    }
    if (size == 0 || (size & 15)) W("\n");
    W("};\n");
    char big[160];
    snprintf(big, sizeof(big), "static const unsigned int g_payloadDllSize = %u;\n", (unsigned)size);
    W(big);

    CloseHandle(out);
    fwprintf(stdout, L"[bin2h] %ls -> %ls (%u bytes)\n", argv[1], argv[2], (unsigned)size);
    return 0;
}
